/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelticketing;

import java.util.Map;

/**
 *
 * @author AIRGG
 */
public class frmTransaksiPrint extends javax.swing.JFrame {

    /**
     * Creates new form frmTransaksiPrint
     */
    Map<String, Object> jsnData;
    public frmTransaksiPrint(Map<String, Object> jsnData) {
        initComponents();
        this.jsnData = jsnData;
        runAwal();
    }
    void runAwal(){
        String idnya = jsnData.get("tmpidtrn").toString();
        String namatp = jsnData.get("namatp").toString();
        String typetpnya = jsnData.get("typetp").toString();
        String jmlpm = jsnData.get("jmlpenumpang").toString();
        String klspm = jsnData.get("klspenumpang").toString();
        String harga = jsnData.get("harga").toString();
        String totalharga = jsnData.get("totalharga").toString();
        String asal = jsnData.get("asal").toString();
        String tujuan = jsnData.get("tujuan").toString();
        String tglberangkat = jsnData.get("tglberangkat").toString();
        String jamberangkat = jsnData.get("jamberangkat").toString();
        String tmptypetp = "Udara";
        if(typetpnya.equals("2")) tmptypetp = "Air";
        if(typetpnya.equals("3")) tmptypetp = "Darat";
        lblIdTrn.setText(idnya);
        lblTypeTp.setText(tmptypetp);
        lblNamaTp.setText(namatp);
        lblJmlPenumpang.setText(jmlpm+" Orang");
        lblKelasPenumpang.setText(klspm);
        lblHarga.setText(harga);
        lblTotalHarga.setText(totalharga);
        lblAsal.setText(asal);
        lblTujuan.setText(tujuan);
        lblTglBerangkat.setText(tglberangkat);
        lblJamBerangkat.setText(jamberangkat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDTrn = new javax.swing.JLabel();
        txtTandaTerima = new javax.swing.JLabel();
        txtNamaTransportasi = new javax.swing.JLabel();
        txtTypeTransportasi = new javax.swing.JLabel();
        txtJmlPenumpang = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtKelasPenumpang = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JLabel();
        txtTglBerangkat = new javax.swing.JLabel();
        txtAsal = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JLabel();
        txtJamBerangkat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblIdTrn = new javax.swing.JLabel();
        lblNamaTp = new javax.swing.JLabel();
        lblTypeTp = new javax.swing.JLabel();
        lblJmlPenumpang = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblKelasPenumpang = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblTglBerangkat = new javax.swing.JLabel();
        lblAsal = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        lblJamBerangkat = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIDTrn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIDTrn.setText("ID Trn");

        txtTandaTerima.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTandaTerima.setText("Tanda Terima");

        txtNamaTransportasi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNamaTransportasi.setText("Nama Transportasi");

        txtTypeTransportasi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTypeTransportasi.setText("Type Transportasi");

        txtJmlPenumpang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtJmlPenumpang.setText("Jml Penumpang");

        txtHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtHarga.setText("Harga");

        txtKelasPenumpang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtKelasPenumpang.setText("Kelas Penumpang");

        txtTujuan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTujuan.setText("Tujuan");

        txtTglBerangkat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTglBerangkat.setText("Tgl  Berangkat");

        txtAsal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAsal.setText("Asal");

        txtTotalHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTotalHarga.setText("Total Harga");

        txtJamBerangkat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtJamBerangkat.setText("Jam Berangkat");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText(":");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText(":");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText(":");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText(":");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText(":");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText(":");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText(":");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText(":");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText(":");

        lblIdTrn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIdTrn.setText("---");

        lblNamaTp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaTp.setText("---");

        lblTypeTp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTypeTp.setText("---");

        lblJmlPenumpang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJmlPenumpang.setText("---");

        lblHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHarga.setText("---");

        lblKelasPenumpang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKelasPenumpang.setText("---");

        lblTujuan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTujuan.setText("---");

        lblTglBerangkat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglBerangkat.setText("---");

        lblAsal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAsal.setText("---");

        lblTotalHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalHarga.setText("---");

        lblJamBerangkat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJamBerangkat.setText("---");

        btnPrint.setText("PRINT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJamBerangkat)
                    .addComponent(txtTglBerangkat)
                    .addComponent(txtTujuan)
                    .addComponent(txtIDTrn)
                    .addComponent(txtNamaTransportasi)
                    .addComponent(txtTypeTransportasi)
                    .addComponent(txtJmlPenumpang)
                    .addComponent(txtKelasPenumpang)
                    .addComponent(txtHarga)
                    .addComponent(txtTotalHarga)
                    .addComponent(txtAsal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel14)
                        .addComponent(jLabel26)
                        .addComponent(jLabel25)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19))
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJamBerangkat)
                    .addComponent(lblTglBerangkat)
                    .addComponent(lblTujuan)
                    .addComponent(lblIdTrn)
                    .addComponent(lblJmlPenumpang)
                    .addComponent(lblKelasPenumpang)
                    .addComponent(lblHarga)
                    .addComponent(lblTotalHarga)
                    .addComponent(lblAsal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNamaTp)
                        .addComponent(lblTypeTp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTandaTerima)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtTandaTerima)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDTrn)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTypeTransportasi)
                            .addComponent(jLabel14)
                            .addComponent(lblTypeTp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaTransportasi)
                            .addComponent(jLabel18)
                            .addComponent(lblNamaTp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(lblJmlPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdTrn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKelasPenumpang)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalHarga)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsal)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTujuan)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTglBerangkat)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJamBerangkat)
                            .addComponent(jLabel26)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKelasPenumpang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAsal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTujuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTglBerangkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJamBerangkat)))
                .addGap(28, 28, 28)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransaksiPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransaksiPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransaksiPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransaksiPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new frmTransaksiPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAsal;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIdTrn;
    private javax.swing.JLabel lblJamBerangkat;
    private javax.swing.JLabel lblJmlPenumpang;
    private javax.swing.JLabel lblKelasPenumpang;
    private javax.swing.JLabel lblNamaTp;
    private javax.swing.JLabel lblTglBerangkat;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JLabel lblTypeTp;
    private javax.swing.JLabel txtAsal;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtIDTrn;
    private javax.swing.JLabel txtJamBerangkat;
    private javax.swing.JLabel txtJmlPenumpang;
    private javax.swing.JLabel txtKelasPenumpang;
    private javax.swing.JLabel txtNamaTransportasi;
    private javax.swing.JLabel txtTandaTerima;
    private javax.swing.JLabel txtTglBerangkat;
    private javax.swing.JLabel txtTotalHarga;
    private javax.swing.JLabel txtTujuan;
    private javax.swing.JLabel txtTypeTransportasi;
    // End of variables declaration//GEN-END:variables
}
